<?php
return array(
'Простая древняя икона'         => array('en' => 'Lesser Ancient Icon'),
'Обычная древняя икона'         => array('en' => 'Ancient Icon'),
'Дорогая древняя икона'         => array('en' => 'Greater Ancient Icon'),
'Бесценная древняя икона'       => array('en' => 'Major Ancient Icon'),
'Простая древняя печать'        => array('en' => 'Lesser Ancient Seal'),
'Обычная древняя печать'        => array('en' => 'Ancient Seal'),
'Дорогая древняя печать'        => array('en' => 'Greater Ancient Seal'),
'Бесценная древняя печать'      => array('en' => 'Major Ancient Seal'),
'Простая древняя чаша'          => array('en' => 'Lesser Ancient Goblet'),
'Обычная древняя чаша'          => array('en' => 'Ancient Goblet'),
'Дорогая древняя чаша'          => array('en' => 'Greater Ancient Goblet'),
'Бесценная древняя чаша'        => array('en' => 'Major Ancient Goblet'),
'Простая древняя корона'        => array('en' => 'Lesser Ancient Crown'),
'Обычная древняя корона'        => array('en' => 'Ancient Crown'),
'Дорогая древняя корона'        => array('en' => 'Greater Ancient Crown'),
'Бесценная древняя корона'      => array('en' => 'Major Ancient Crown'),
'Выберите количество игроков в группе'    => array('en' => 'Select the group size'),
'Распределить на группу'        => array('en' => 'Distribute to the group'),
'Ваши очки бездны'              => array('en' => 'Your abyss point'),
'Сброс'                         => array('en' => 'Clear'),
'Отдать одному'                 => array('en' => 'Give to one'),
'Сейчас на руках'               => array('en' => 'Now on hands'),
'Выберите пользователя которому собираетесь отдать все указанные итемы'    => array('en' => 'Select the user that are going to give all of the item is'),
'Пользователь'                  => array('en' => 'User'),
);